name: general-redneck
recipe: drupal8
config:
  webroot: web
  xdebug: true
  php: "7.4"
tooling:
  drush:
    service: appserver
    cmd: "drush --root=/app/web --uri=http://general-redneck.lndo.site"
