vagrant_hostname: generalredneck.local
vagrant_machine_name: "{{ vagrant_hostname }}"
vagrant_ip: 0.0.0.0
drupal_install_site: false
drupal_build_composer_project: false
drupal_composer_install_dir: "/var/www/drupalvm"
drupal_major_version: 8
drupalvm_webserver: nginx

php_version: "7.0"
installed_extras:
  - adminer
  # - blackfire
  # - drupalconsole
  - drush
  # - elasticsearch
  # - java
  - mailhog
  # - memcached
  # - newrelic
  # - nodejs
  - pimpmylog
  # - redis
  # - ruby
  # - selenium
  # - tideways
  # - upload-progress
  - varnish
  # - xdebug
  # - xhprof
