_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
module:
  automated_cron: 0
  block: 0
  block_content: 0
  breakpoint: 0
  captcha: 0
  checklistapi: 0
  ckeditor: 0
  color: 0
  config: 0
  contact: 0
  contextual: 0
  ctools: 0
  datetime: 0
  datetime_range: 0
  dblog: 0
  dynamic_page_cache: 0
  editor: 0
  field: 0
  field_ui: 0
  file: 0
  filter: 0
  fontawesome: 0
  generalredneck_custom: 0
  google_analytics: 0
  image: 0
  keyboard_styles: 0
  libraries: 0
  link: 0
  markdown: 0
  menu_ui: 0
  metatag: 0
  metatag_hreflang: 0
  metatag_mobile: 0
  metatag_open_graph: 0
  metatag_views: 0
  nocaptcha_recaptcha: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  path_alias: 0
  quickedit: 0
  redirect: 0
  seo_checklist: 0
  shortcut: 0
  system: 0
  taxonomy: 0
  text: 0
  token: 0
  toolbar: 0
  update: 0
  user: 0
  views_ui: 0
  xmlsitemap_engines: 0
  menu_link_content: 1
  pathauto: 1
  xmlsitemap: 1
  views: 10
  standard: 1000
theme:
  bartik: 0
  seven: 0
  stable: 0
  classy: 0
  bootstrap5: 0
  generalredneck_b5: 0
profile: standard
