_core:
  default_config_hash: AyT9s8OUcclfALRE_imByOMgtZ19eOlqdF6zI3p7yqo
langcode: en
uuid: 47657f7e-eb6b-4aa4-83fb-1ddf2b3c986b
name: 'Just A General Redneck''s Blog'
mail: generalredneck@gmail.com
slogan: 'Coding, Testing, Drupal, and Stuff!'
page:
  403: /user
  404: ''
  front: /node
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
mail_notification: ''
